# Autogenerated wrapper script for xapian_jll for x86_64-linux-gnu-cxx11
export libxapian

using Zlib_jll
using Libuuid_jll
using ICU_jll
JLLWrappers.@generate_wrapper_header("xapian")
JLLWrappers.@declare_library_product(libxapian, "libxapian.so.30")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Libuuid_jll, ICU_jll)
    JLLWrappers.@init_library_product(
        libxapian,
        "lib/libxapian.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
